[package]
name = "datachannel"
version = "0.1.0"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"

[dependencies]
datachannel-sys = { path = "datachannel-sys", version = "0.1.0" }
derivative = "2.1"
lazy_static = "1.4"
log = "0.4"
parking_lot = "0.11"
webrtc-sdp = "0.3"

[dev-dependencies]
crossbeam-channel = "0.4"
env_logger = "0.7"

[features]
static = ["datachannel-sys/static"]
