[package]
name = "datachannel"
version = "0.1.0"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"

[dependencies]
datachannel-sys = { path = "datachannel-sys", version = "0.1.0" }
lazy_static = "1.4"
log = "0.4"

[dev-dependencies]
crossbeam-channel = "0.4"
env_logger = "0.7"