[package]
name = "datachannel"
version = "0.1.0"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"

[dependencies]
crossbeam-utils = "0.7"
datachannel-sys = { path = "datachannel-sys", version = "0.1.0" }
lazy_static = "1.4"
log = "0.4"
serde = {version = "1.0" , features = ["derive"], optional = true}
webrtc-sdp = "0.3"

[features]
serialize = ["serde", "webrtc-sdp/serialize"]

[dev-dependencies]
crossbeam-channel = "0.4"
env_logger = "0.7"
