[package]
name = "datachannel-sys"
version = "0.1.0"
authors = ["Romain Leroux <romain@leroux.dev>"]
edition = "2018"
links = "datachannel"

[dependencies]
openssl = "0.10"

[build-dependencies]
bindgen = "0.53"
cmake = "0.1"
cpp_build = { version = "0.5", optional = true }

[features]
static = ["openssl/vendored", "cpp_build"]